import { StyleSheet, Dimensions } from "react-native";
import { Colors as BrandColors } from "../constants/Colors";

const { width } = Dimensions.get("window");

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F9FAFB",
  },
  subHeader: {
    paddingHorizontal: 20,
    paddingVertical: 16,
    backgroundColor: "transparent",
  },
  activeOrdersLabel: {
    fontSize: 14,
    color: "#6B7280",
    fontWeight: '500',
  },
  activeOrdersCount: {
    fontSize: 18,
    fontWeight: "700",
    color: "#111827",
    marginTop: 4,
  },
  headerTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  clearCartButton: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 8,
    paddingHorizontal: 16,
    backgroundColor: '#fff',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  clearCartText: {
    fontSize: 14,
    color: "#6B7280",
    marginRight: 6,
    fontWeight: "500",
  },
  scrollView: {
    flex: 1,
  },
  scrollViewContent: {
    paddingBottom: 40,
  },
  summaryCard: {
    backgroundColor: "#fff",
    borderRadius: 30,
    padding: 24,
    marginHorizontal: 16,
    marginBottom: 20,
    elevation: 4,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.05,
    shadowRadius: 20,
  },
  cardTopRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 16,
  },
  badgePill: {
    backgroundColor: '#FEF3C7',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 12,
    marginBottom: 12,
    alignSelf: 'flex-start',
  },
  badgeText: {
    fontSize: 11,
    fontWeight: "800",
    color: '#D97706',
    textTransform: 'uppercase',
  },
  restaurantName: {
    fontSize: 24,
    fontWeight: "800",
    color: "#111827",
  },
  itemCountText: {
    fontSize: 15,
    color: "#9CA3AF",
    marginTop: 4,
    fontStyle: 'italic',
  },
  subtotalContainer: {
    alignItems: "flex-end",
  },
  subtotalValue: {
    fontSize: 22,
    fontWeight: "800",
    color: "#3d241c",
  },
  subtotalLabel: {
    fontSize: 14,
    color: "#9CA3AF",
    fontWeight: "500",
  },
  deliveryTimeContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 8,
  },
  deliveryTimeTextInline: {
    fontSize: 14,
    color: "#6B7280",
    fontWeight: "500",
    marginLeft: 4,
  },
  itemPreviewList: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    marginBottom: 24,
    marginTop: 12,
  },
  itemPreviewImage: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: "#F9FAFB",
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  primaryButton: {
    backgroundColor: "#FF5221", // Specific orange from screenshot
    height: 48,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 12,
  },
  primaryButtonText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "800",
  },
  secondaryButton: {
    height: 48,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#F3F4F6',
  },
  secondaryButtonContent: {
    flexDirection: "row",
    alignItems: "center",
  },
  secondaryButtonText: {
    fontSize: 15,
    color: "#111827",
    fontWeight: "700",
    marginRight: 6,
  },
  detailsContainer: {
    marginTop: 16,
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: "#F3F4F6",
  },
  detailItem: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
  },
  detailItemName: {
    fontSize: 15,
    color: "#4B5563",
    fontWeight: '500',
  },
  detailItemPrice: {
    fontSize: 15,
    fontWeight: "700",
    color: "#111827",
  },
  emptyCartContainer: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 60,
  },
  emptyCartText: {
    fontSize: 16,
    color: "#6B7280",
    marginTop: 20,
    fontWeight: '500',
  },
  promoCard: {
    backgroundColor: "transparent",
    borderRadius: 40,
    padding: 40,
    alignItems: 'center',
    marginTop: 0,
    marginHorizontal: 20,
    borderWidth: 2,
    borderColor: '#E5E7EB',
    borderStyle: 'dashed',
  },
  promoIconContainer: {
    width: 70,
    height: 70,
    borderRadius: 35,
    backgroundColor: '#fff',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 24,
    elevation: 4,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 10,
  },
  promoTitle: {
    fontSize: 22,
    fontWeight: '800',
    color: '#111827',
    marginBottom: 12,
    textAlign: 'center',
  },
  promoSubtitle: {
    fontSize: 15,
    color: '#6B7280',
    textAlign: 'center',
    marginBottom: 30,
    lineHeight: 22,
    fontWeight: '500',
    paddingHorizontal: 20,
  },
  promoButton: {
    backgroundColor: '#1c252e', // Dark navy from screenshot
    paddingHorizontal: 36,
    height: 48,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  promoButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '800',
  },
});