import { StyleSheet } from 'react-native';
import { Colors as BrandColors } from '../constants/Colors';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
  },
  cartTotal: {
    color: '#fff',
    fontSize: 15,
    fontWeight: '700',
  },
  cartCount: {
    color: '#fff',
    fontSize: 15,
    fontWeight: '600',
    marginLeft: 8,
  },
  viewCartButton: {
    position: 'absolute',
    bottom: 20,
    left: 20,
    right: 20,
    backgroundColor: BrandColors.primary,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    height: 48,
    paddingHorizontal: 20,
    borderRadius: 12,
    elevation: 5,
  },
  cartInfo: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 8,
    backgroundColor: '#fff',
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#1F2937',
    marginLeft: 12,
  },
  backButton: {
    padding: 4,
  },
  searchContainer: {
    backgroundColor: '#fff',
    paddingHorizontal: 20,
    paddingTop: 8,
    paddingBottom: 16,
    zIndex: 10,
  },
  searchWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff',
    borderRadius: 12,
    paddingHorizontal: 16,
    height: 48,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    elevation: 4,
  },
  searchIcon: {
    marginRight: 10,
  },
  clearIcon: {
    padding: 8,
  },
  searchInput: {
    flex: 1,
    fontSize: 16,
    color: '#1F2937',
    paddingVertical: 10,
  },
  loadingText: {
    marginTop: 10,
    fontSize: 16,
    color: '#666',
  },
  errorContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  errorText: {
    fontSize: 16,
    color: BrandColors.primary,
    textAlign: 'center',
    marginBottom: 20,
  },
  retryButton: {
    backgroundColor: BrandColors.primary,
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 8,
  },
  retryButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: 'bold',
  },
  listContainer: {
    paddingHorizontal: 20,
    paddingBottom: 20,
    paddingTop: 0,
  },
  searchLoading: {
    marginLeft: 8,
  },
  fullLoading: {
    marginVertical: 20,
  },
  restaurantCard: {
    backgroundColor: '#fff',
    borderRadius: 16,
    marginBottom: 16, // Reduced from 20
    elevation: 4,
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  restaurantImage: {
    width: '100%',
    height: 200,
    borderTopLeftRadius: 12,
    borderTopRightRadius: 12,
    backgroundColor: '#F3F4F6',
  },
  restaurantInfo: {
    padding: 16, // Reduced from 20
  },
  restaurantName: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#1F2937',
    marginBottom: 4,
  },
  cuisineType: {
    fontSize: 13,
    color: '#6B7280',
    marginBottom: 8,
  },
  restaurantMeta: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginBottom: 8,
  },
  metaText: {
    fontSize: 13,
    color: '#4B5563',
  },
  address: {
    fontSize: 13,
    color: '#6B7280',
    fontStyle: 'italic',
  },
  menuItemsContainer: {
    padding: 16,
    borderTopWidth: 1,
    borderTopColor: '#E5E7EB',
  },
  menuTitle: {
    fontSize: 17,
    fontWeight: 'bold',
    color: '#1F2937',
    marginBottom: 12,
  },
  menuItem: {
    flexDirection: 'row',
    marginBottom: 12, // Reduced from 16
    backgroundColor: '#fff',
    borderRadius: 8,
    padding: 8,
    elevation: 2,
  },
  menuItemImageContainer: {
    position: 'relative',
    width: 110,
    height: 110,
  },
  menuItemQuantitySelector: {
    position: 'absolute',
    bottom: 12,
    right: 12,
    zIndex: 20,
  },
  menuItemImage: {
    width: 110,
    height: 110,
    borderRadius: 12,
    backgroundColor: '#F9FAFB',
  },
  menuItemInfo: {
    flex: 1,
    marginRight: 16,
    justifyContent: 'center',
    minWidth: 0,
  },
  menuItemName: {
    fontSize: 15,
    fontWeight: '600',
    color: '#1F2937',
    marginBottom: 4,
    flexWrap: 'wrap',
  },
  menuItemDescription: {
    fontSize: 13,
    color: '#6B7280',
    marginBottom: 4,
    flexWrap: 'wrap',
  },
  menuItemPrice: {
    fontSize: 15,
    fontWeight: '600',
    color: BrandColors.primary,
    flexWrap: 'wrap',
  },
  addButtonOverlay: {
    position: 'absolute',
    top: 6,
    right: 6,
  },
  addButtonCircle: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: BrandColors.primary,
    justifyContent: "center",
    alignItems: "center",
    elevation: 4,
  },
  quantityOverlay: {
    position: 'absolute',
    top: 6,
    right: 6,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'transparent',
    borderRadius: 18,
    paddingHorizontal: 2,
    paddingVertical: 2,
    maxWidth: '100%',
  },
  quantityOverlayButton: {
    marginHorizontal: 2,
  },
  quantityOverlayIconCircle: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(229, 231, 235, 0.8)',
    elevation: 2,
  },
  quantityOverlayIconCircleDisabled: {
    backgroundColor: 'rgba(243, 244, 246, 0.95)',
    borderColor: 'rgba(229, 231, 235, 0.5)',
  },
  quantityOverlayNumberCircle: {
    minWidth: 30,
    height: 28,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 8,
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: 'rgba(229, 231, 235, 0.8)',
    elevation: 2,
  },
  quantityOverlayText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#111827',
  },
  cartButton: {
    position: 'absolute',
    bottom: 50,
    left: 20,
    right: 20,
    backgroundColor: BrandColors.primary,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    height: 48,
    paddingHorizontal: 20,
    borderRadius: 12,
    elevation: 5,
  },
  cartButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
    marginLeft: 8,
  },
  cartButtonPrice: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '700',
  },
  categoryItem: {
    width: 100,
    height: 100,
    borderRadius: 16,
    marginRight: 16,
    overflow: 'hidden',
  },
  categoryIcon: {
    width: '100%',
    height: '100%',
  },
  categoryName: {
    fontSize: 14,
    fontWeight: '600',
    color: '#1F2937',
    textAlign: 'center',
    marginTop: 4,
  },
  viewAllMenu: {
    paddingVertical: 12,
    alignItems: 'center',
    borderTopWidth: 1,
    borderTopColor: '#F3F4F6',
    marginTop: 8,
  },
  viewAllMenuText: {
    fontSize: 15,
    fontWeight: '700',
    color: BrandColors.primary,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
});
