import { StyleSheet } from 'react-native';
import { Colors as BrandColors } from '../constants/Colors';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
  },
  headerContainer: {
    width: '100%',
    height: 350,
    backgroundColor: '#fff',
    marginBottom: 16,
  },
  restaurantImage: {
    width: '100%',
    height: 250,
    backgroundColor: '#F3F4F6',
  },
  floatingHeader: {
    position: 'absolute',
    left: 16,
    right: 16,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    zIndex: 10,
  },
  iconButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 3,
  },
  infoCard: {
    position: 'absolute',
    bottom: 0,
    left: 20,
    right: 20,
    backgroundColor: '#fff',
    borderRadius: 24, // 24px already good
    padding: 24,
    elevation: 8,
    zIndex: 5,
  },
  infoCardHeader: {
    marginBottom: 6,
  },
  restaurantName: {
    fontSize: 22,
    fontWeight: '700',
    color: '#1F2937',
    marginBottom: 4,
  },
  deliveryTimeBadge: {
    backgroundColor: '#FFF7ED', // Soft orange
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
    alignSelf: 'flex-start',
    marginBottom: 12,
  },
  deliveryTimeText: {
    color: BrandColors.primary,
    fontSize: 14,
    fontWeight: '700',
  },
  ratingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  ratingText: {
    fontSize: 15,
    fontWeight: 'bold',
    color: '#1F2937',
    marginLeft: 6,
  },
  reviewsText: {
    fontSize: 14,
    color: '#6B7280',
    marginLeft: 6,
  },
  detailsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  detailsText: {
    fontSize: 14,
    color: '#4B5563',
    marginLeft: 8,
    fontWeight: '500',
  },
  statusRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  statusText: {
    fontSize: 14,
    color: '#10B981',
    fontWeight: '700',
    marginLeft: 8,
  },
  dot: {
    color: '#9CA3AF',
    fontSize: 14,
  },
  closesText: {
    fontSize: 14,
    color: '#6B7280',
  },
  searchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    marginHorizontal: 20, 
    marginTop: 24,
    marginBottom: 12, 
    borderRadius: 14,
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    elevation: 5,
  },
  searchIcon: {
    marginRight: 12,
  },
  searchInput: {
    flex: 1,
    fontSize: 16,
    color: '#1F2937',
    padding: 0,
  },
  clearSearchButton: {
    marginLeft: 8,
    padding: 4,
  },
  menuItem: {
    flexDirection: 'row',
    backgroundColor: '#fff',
    borderRadius: 16,
    marginBottom: 12, // Reduced from 16
    marginHorizontal: 20, // 20px
    padding: 12,
    borderWidth: 1,
    borderColor: '#F3F4F6',
    elevation: 3,
  },
  menuItemImageContainer: {
    position: 'relative',
    width: 110,
    height: 110,
    borderRadius: 12,
    overflow: 'hidden',
  },
  menuItemImage: {
    width: '100%',
    height: '100%',
    backgroundColor: '#F9FAFB',
  },
  menuItemQuantitySelector: {
    position: 'absolute',
    bottom: 12,
    right: 12,
    zIndex: 10,
  },
  menuItemInfo: {
    flex: 1,
    marginRight: 16,
    minWidth: 0,
    justifyContent: 'center',
  },
  menuItemName: {
    fontSize: 15,
    fontWeight: '600',
    color: '#1F2937',
    marginBottom: 4,
    flexWrap: 'wrap',
  },
  menuItemDescription: {
    fontSize: 14,
    color: '#6B7280',
    marginBottom: 4,
    flexWrap: 'wrap',
  },
  menuItemPrice: {
    fontSize: 15,
    fontWeight: '600',
    color: BrandColors.primary,
    flexWrap: 'wrap',
  },
  quantityOverlay: {
    position: 'absolute',
    top: 6,
    right: 6,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'transparent',
    borderRadius: 50,
    paddingHorizontal: 2,
    paddingVertical: 2,
    maxWidth: '100%',
  },
  quantityOverlayButton: {
    marginHorizontal: 2,
  },
  quantityOverlayIconCircle: {
    width: 28,
    height: 28,
    borderRadius: 50,
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(229, 231, 235, 0.8)',
    elevation: 2,
  },
  quantityOverlayIconCircleDisabled: {
    backgroundColor: 'rgba(243, 244, 246, 0.95)',
    borderColor: 'rgba(229, 231, 235, 0.5)',
  },
  quantityOverlayNumberCircle: {
    minWidth: 30,
    height: 28,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 8,
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
    borderRadius: 50,
    borderWidth: 1,
    borderColor: 'rgba(229, 231, 235, 0.8)',
    elevation: 2,
  },
  quantityOverlayText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#111827',
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  loadingText: {
    marginTop: 10,
    fontSize: 16,
    color: '#666',
  },
  errorContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  errorText: {
    fontSize: 16,
    color: BrandColors.primary,
    textAlign: 'center',
  },
  viewCartButton: {
    backgroundColor: BrandColors.primary,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    height: 48,
    paddingHorizontal: 20,
    borderRadius: 12,
    elevation: 5,
  },
  cartInfo: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  cartCount: {
    color: '#fff',
    fontSize: 15,
    fontWeight: '600',
    marginLeft: 8,
  },
  cartTotal: {
    color: '#fff',
    fontSize: 15,
    fontWeight: '700',
  },
  noItemsContainer: {
    padding: 40,
    justifyContent: 'center',
    alignItems: 'center',
  },
  noItemsText: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#6B7280',
  },
});
