import { StyleSheet } from 'react-native';
import { Colors as BrandColors } from '../constants/Colors';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
  },
  header: {
    justifyContent: "flex-end",
    paddingHorizontal: 20, 
    paddingBottom: 24,
    borderBottomLeftRadius: 30,
    borderBottomRightRadius: 30,
    overflow: "hidden",
    elevation: 8,
    marginBottom: 4, // create space below header
  },
  brandHeaderContent: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
    marginBottom: 16,
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
    marginBottom: 2,
  },
  brandTextContainer: {
    flex: 1,
  },
  brandGreeting: {
    fontSize: 13,
    fontWeight: "700",
    color: "rgba(255, 255, 255, 0.85)",
    marginBottom: 2,
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  title: {
    fontSize: 24,
    fontWeight: "700",
    color: "#FFFFFF",
    // @ts-ignore
    textShadow: '0px 2px 8px rgba(0, 0, 0, 0.15)',
  },
  brandIconContainer: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: 'rgba(255, 255, 255, 0.25)',
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 16,
  },
  searchInputContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderRadius: 12,
    paddingHorizontal: 16,
    height: 48,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    // @ts-ignore
    boxShadow: "0px 8px 16px rgba(0, 0, 0, 0.08)",
    elevation: 6,
  },
  cuisineItemsScroll: {
    paddingLeft: 20,
    paddingBottom: 4,
  },
  searchIcon: {
    marginRight: 10,
  },
  clearIcon: {
    padding: 4,
  },
  searchInput: {
    flex: 1,
    fontSize: 16,
    color: "#1F2937",
    fontWeight: '500',
  },
  scrollContent: {
    paddingTop: 24,
  },
  section: {
    marginTop: 32,
    marginBottom: 8,
  },
  sectionEmpty: {
    marginTop: 12,
    marginBottom: 0,
  },
  sectionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
    paddingHorizontal: 20,
  },
  sectionTitleContainer: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    marginRight: 16,
  },
  sectionAccent: {
    width: 4,
    height: 24,
    backgroundColor: BrandColors.primary,
    borderRadius: 2,
    marginRight: 10,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: "700",
    color: "#111827",
    letterSpacing: -0.5,
  },
  recentSearches: {
    flexDirection: "row",
    flexWrap: "wrap",
    paddingHorizontal: 20,
  },
  recentSearchItem: {
    backgroundColor: "#F3F4F6",
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 12,
    marginRight: 8,
    marginBottom: 8,
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  recentSearchText: {
    color: "#4B5563",
    fontSize: 13,
    fontWeight: '500',
  },
  noRecentSearches: {
    paddingHorizontal: 20,
    fontSize: 14,
    color: "#9CA3AF",
    textAlign: "left",
    marginBottom: 8,
  },
  cuisineSection: {
    marginTop: 40,
    marginBottom: 0,
  },
  cuisineName: {
    fontSize: 16,
    fontWeight: "700",
    color: "#4B5563",
    marginBottom: 12,
    paddingHorizontal: 20,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  restaurantsGrid: {
    paddingHorizontal: 20,
  },
  modernRestaurantCard: {
    height: 200,
    width: 280,
    borderRadius: 16,
    marginBottom: 12,
    marginRight: 16,
    backgroundColor: '#000',
    overflow: 'hidden',
    // @ts-ignore
    boxShadow: "0px 4px 8px rgba(0, 0, 0, 0.1)",
    elevation: 4,
  },
  modernRestaurantImage: {
    width: '100%',
    height: '100%',
    position: 'absolute',
  },
  cardGradient: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    height: '60%',
  },
  modernCardContent: {
    flex: 1,
    justifyContent: 'flex-end',
    padding: 16,
  },
  cardTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 6,
  },
  modernRestaurantName: {
    fontSize: 20,
    fontWeight: '700',
    color: '#FFF',
    flex: 1,
    marginRight: 10,
    textShadowColor: 'rgba(0, 0, 0, 0.5)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 3,
  },
  modernRatingBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(252, 90, 35, 0.9)',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
  },
  modernRatingText: {
    color: '#FFF',
    fontWeight: 'bold',
    fontSize: 14,
    marginLeft: 4,
  },
  cardBottomRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  modernRestaurantCuisine: {
    color: 'rgba(255, 255, 255, 0.9)',
    fontSize: 14,
    fontWeight: '600',
  },
  modernDeliveryInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
  },
  modernDeliveryText: {
    color: '#FFF',
    fontSize: 12,
    fontWeight: 'bold',
  },
  horizontalScrollPadding: {
    paddingLeft: 20, // 20px
    paddingRight: 4,
  },
  menuItemCard: {
    width: 160,
    backgroundColor: "#fff",
    borderRadius: 16,
    marginRight: 16,
    marginBottom: 8,
    // @ts-ignore
    boxShadow: "0px 4px 12px rgba(0, 0, 0, 0.08)",
    elevation: 4,
    overflow: 'hidden',
  },
  imageContainer: {
    width: '100%',
    aspectRatio: 1,
    overflow: 'visible',
    backgroundColor: '#F3F4F6',
    position: 'relative',
  },
  menuItemQuantitySelector: {
    position: 'absolute',
    bottom: 12,
    right: 12,
    zIndex: 20,
  },
  menuItemImage: {
    width: "100%",
    height: "100%",
  },
  menuItemInfo: {
    padding: 12,
  },
  menuItemName: {
    fontSize: 14,
    fontWeight: "600",
    color: "#1F2937",
    marginBottom: 4,
    lineHeight: 20,
    height: 40, // Fixed height for 2 lines
  },
  menuItemPrice: {
    fontSize: 15,
    fontWeight: "bold",
    color: BrandColors.primary,
  },
  loader: {
    marginTop: 20,
  },
  noCuisinesText: {
    fontSize: 15,
    color: "#666",
    textAlign: "center",
    marginTop: 10,
  },
  searchEmptyContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingTop: 100,
    paddingBottom: 40,
  },
  searchEmptyText: {
    fontSize: 16,
    color: "#9CA3AF",
    marginTop: 16,
    fontWeight: '600',
  },
});
